#!/bin/bash
source /home/LAB/anaconda3/bin/activate /home/LAB/hanzy/.conda/envs/SEAL_OGB
nohup srun --gres=gpu:1 -t 2-0:0 python explainer_main.py --explain-node=300 --dataset=USAir --model ogb_GCN --epoch 100 --gpu > log_explain_USAir.txt 2>&1 &
