#!/bin/bash
source /home/LAB/anaconda3/bin/activate /home/LAB/hanzy/.conda/envs/SEAL_OGB
nohup srun --gres=gpu:1 -t 2-0:0 python train.py --dataset movie --epochs 1000 --multi_label True --gpu> log_train_movie_nodeEncoder.txt 2>&1 &
