#!/bin/bash
source /home/LAB/anaconda3/bin/activate /home/LAB/hanzy/.conda/envs/SEAL_OGB
nohup srun --gres=gpu:1 -t 2-0:0 python train.py --dataset movie --epochs 10000 --multi_label True --gpu --model ogb_GCN > log_train_movie.txt 2>&1 &
