#!/bin/bash
source /home/LAB/anaconda3/bin/activate /home/LAB/hanzy/.conda/envs/SEAL_OGB
nohup srun --gres=gpu:1 -t 2-0:0 python train.py --dataset=USAir --epochs 1000 --model ogb_GCN --single_edge_label True --gpu > log_train_USAir.txt 2>&1 &
