0	0	'gambling in a rigged casino: the adversarial multi-armed bandit problem,'	1995,	pp. 322-331.
1	0	cryptographic primitives based on hard learning problems.	1993.	pages 24.1-24.10,
2	0	weakly learning dnf and characterizing statistical query learning using fourier analysis.	(1994).	pp. 253-262.
3	0	how to use expert advice.	1993.	pages 382-391,
4	0	learning to order things.	1997.	-
5	0	applying the weak learning framework to understand and improve c4.5.	1996.	pages 96-104.
6	0	improving performance in neural networks using a boosting algorithm.	1993.	pages 42-49.
7	0	improving performance in neural networks using a boosting algorithm,	1993,	42-49.
8	0	a general lower bound on the number of examples needed for learning.	(1988).	-
9	0	a general lower bound on the number of examples needed for learning.	1989.	247-261,
10	0	optimal universal learning and prediction of probabilistic concepts.	1995.	page 233.
11	0	adaptive game playing using multiplicative weights. games and economic behavior,	-	-
12	0	boosting a weak learning algorithm by majority.	1990.	pages 202-216,
13	0	information, prediction, and query by committee.	-	-
14	0	an improved boosting algorithm and its implications on learning complexity.	1992.	pages 391-398,
15	0	unsupervised learning of distributions on binary vectors using two layer networks,	(1992),	-
16	0	efficient learning of typical finite automata from random walks.	(1993).	315-324).
17	0	data filtering and distribution modeling algorithms for machine learning.	1993.	-
18	0	selective sampling using the query by committee algorithm.	-	-
19	0	a decision-theoretic generalization of on-line learning and an applicationto boosting.	1995.	pages 23-37.
20	0	a decision-theoretic generalization of on-line learning and an application to boosting.	(1995.)	904.
21	0	a decision-theoretic generalization of on-line learning and an application to boosting.	(1995).	-
22	0	learning to model sequences generated by switching distributions.	1995.	pages 4150,
23	0	efficient algorithms for learning to play repeated games against computationally bounded adversaries.	1995.	-
24	0	predicting a binary sequence almost as well as the optimal biased coin.	1996.	pages 89-98,
25	0	game theory, on-line prediction and boosting.	1996.	pages 325-332,
26	0	experiments with a new boosting algorithm.	1996.	-
27	0	a decision-theoretic generalization of on-line learning and an application to boosting.	1996a.	-
28	0	experiments with a new boosting algorithm.	1996b.	-
29	0	a decision-theoretic generalization of on-line learning and an application to boosting.	(1997).	119-139.
30	0	using and combining predictors that specialize.	(1997).	-
31	0	selective sampling using the query by committee algorithm.	(1997).	133-168.
32	0	learning under persistent drift.	1997.	pages 94-108.
33	0	learning binary relations and total orders.	1989.	46-51.
34	0	exact identification of circuits using fixed points of amplification functions.	1990.	pages 193-202.
35	0	on the sample complexity of weak learning.	1990.	pages 217-231.
36	0	learning binary relations and total orders.	1989.	-
37	0	on the complexity of teaching.	(1991).	303-314).
38	0	learning binary relations and total orders.	1993.	1006-1034,
39	0	on the complexity of teaching.	1995.	20-31,
40	0	equivalence of models for polynomial learnability.	1988.	pp. 42-55,
41	0	equivalence of models for polynomial learnability.	1991.	129-161,
42	0	bounds on the sample complexity of bayesian learning using information theory and the vc dimension.	1991.	pages 61-74.
43	0	schapire (1991). `bounds on the sample complexity of bayesian learning using information theory and the vc dimension',	-	-
44	0	bounds on the sample complexity of bayesian learning using information theory and the vc dimension.	(1992).	-
45	0	rigorous learning curve bounds from statistical mechanics.	-	pages 76-87,
46	0	rigourous learning curve bounds from statistical mechanics.	1996.	195-236,
47	0	predicting nearly as well as the best pruning of a decision tree.	1995.	pages 61-68,
48	0	a comparison of new and old algorithms for a mixture estimation problem.	1995.	pages 69-78,
49	0	on-line portfolio selection using multiplicative upyears.	1996.	pages 243-251.
50	0	a comparison of new and old algorithms for a mixture estimation problem,	(1996b),	-
51	0	predicting nearly as well as the best pruning of a decision tree.	(1997).	51-68.
52	0	a comparison of new and old algorithms for a mixture estimation problem.	1997.	-
53	0	reasoning with characteristic models.	-	pages 34-39.
54	0	b (1995) horn approximations of empirical data.	-	129-145.
55	0	on the learnability of boolean formulae.	1987.	pages 285-295,
56	0	recent results on boolean concept learning.	1987b.	pages 337-352.
57	0	learning in the presence of malicious errors.	(1988).	-
58	0	thoughts on hypothesis boosting.	1988.	-
59	0	cryptographic limitations on learning boolean formulae and finite automata.	1989.	pages 433444,
60	0	a polynomial-time algorithm for learning k-variable pattern languages from examples.	1989.	pages 57-71,
61	0	the computational complexity of machine learning.	1990.	-
62	0	performance evaluation of protocols for distributed systems: an alternative to message counting.	1990.	pages 441-445,
63	0	(1990) efficient distribution-free learning of probabilistic concepts.	-	382-391).
64	0	oblivious pac learning of concepts hierarchies.	1992.	pp. 215-222.
65	0	toward efficient agnostic learning.	1992.	pages 341-352.
66	0	learning in the presence of malicious errors.	1993.	807-837,
67	0	efficient noise-tolerant learning from statistical queries.	1993.	pages 392-401.
68	0	learning from a population of hypotheses.	1993.	pages 101-110,
69	0	on the learnabil-ity of discrete distributions.	1994.	-
70	0	an introduction to computational learning theory.	1994.	-
71	0	efficient distribution-free probabilistic concepts.	1994.	-
72	0	cryptographic limitations on learning boolean formulae and finite automata.	(1994).	41 , 67-95.
73	0	toward efficient agnostic learning.	-	-
74	0	learning boolean formulas,	(1994a),	1298-1328.
75	0	efficient learning of typical finite automata from random walks.	1994.	pages 273-282.
76	0	an experimental and theoretical comparison of model selection methods.	1995.	-
77	0	'a bound on the error of cross validation using the approximation and estimation rates, with consequences for training-test split', neural information processing 8,	(1996).	pp. 183-189.
78	0	mansour (1996). on the boosting ability of top-down decision tree learning algorithms.	-	-
79	0	an experimental and theoretical comparsion of model selection methods.	(1997).	750.
80	0	'an information-theoretic analysis of hard and soft assignment methods for clustering,'	1997.	-
81	0	testing problems with sub-learning sample complexity.	1998.	-
82	0	finite-sample convergence rates for q-learning and indirect algorithms.	1999.	-
83	0	a sparse sampling algorithm for near-optimal planning in large markov decision processes. 1999.	-	-
84	0	training algorithms for linear classifiers.	1996.	pages 298-306.
85	0	hypothesis schemas,	-	-
86	0	a new approach to unsupervised learning in deterministic environments.	(1987).	(pp. 364-375),
87	0	diversity-based inference of finite automata.	(1987).	(pp. 78-87).
88	0	inference of finite automata using homing sequences.	(1989).	pp. 411-420.
89	0	'the md5 message-digest algorithm,' network working group request for comments rfc 1321,	1993	-
90	0	inference of finite automata using homing sequences.	(1993).	299-347.
91	0	diversity-based inference of finite automata.	1994.	555-589,
92	0	boosting the margin: a new explanation for the effectiveness of voting methods.	-	-
93	0	diversity-based inference of finite automata.	(1988).	-
94	0	on the strength of weak learnability.	1989,	pp. 28-33.
95	0	the strength of weak learnability.	1990.	197-227,
96	0	'the emerging theory of average case complexity',	1990.	-
97	0	the design and analysis of efficient learning algorithms.	1992.	-
98	0	learning probabilistic read-once formulas on product distributions.	1991.	-
99	0	the design and analysis of ef ficient learning algorithms.	1992.	-
100	0	learning sparse multivariate polynomial over a field with queries and counterexamples.	1993.	-
101	0	on the worst-case analysis of temporal-difference learning algorithms.	(1994).	pages 266-274.
102	0	'a decision theoretic generalization of on-line learning and its application to boosting'.	1995.	23-27,
103	0	learning sparse multivariate polynomials over a field with queries and counterexamples.	1996.	201-213,
104	0	private communication.	(1996),	-
105	0	boosting the margin: a new explanation for the effectiveness of voting methods,	1997.	-
106	0	`stacked generalization',	(1992),	241-259.
107	0	using output codes to boost multiclass learning problems.	1997.	pages 313-321,
108	0	using output codes to boost multiclass learning problems.	(1997).	-
109	0	improved boosting algorithms using confidence-rated predictions,	(1998),	43
110	0	a system for multiclass multi-label text categorization.	1998.	-
111	0	improved boosting algorithms using confidence-rated predictions.	-	-
112	1	p. auer
113	1	n. cesa-bianchi
114	1	y. freund
115	1	r. e. schapire,
116	1	a. blum
117	1	m. furst
118	1	m. j. kearns
119	1	richard j. lipton.
120	1	blum
121	1	a.
122	1	furst
123	1	m.
124	1	jackson
125	1	j.
126	1	kearns
127	1	m.
128	1	mansour
129	1	y.
130	1	& rudich
131	1	s.
132	1	nicolo cesa-bianchi
133	1	yoav freund
134	1	david p. helmbold
135	1	david haussler
136	1	robert e. schapire
137	1	manfred k. warmuth.
138	1	william w. cohen
139	1	rob schapire
140	1	yoram singer.
141	1	t. g. dietterich
142	1	m. kearns
143	1	y. mansour.
144	1	h. drucker
145	1	r. schapire
146	1	p. simard.
147	1	h. druker
148	1	r. schapire
149	1	p. simard,
150	1	ehrenfeucht
151	1	a.
152	1	haussler
153	1	d.
154	1	kearns
155	1	m.
156	1	valiant
157	1	l.
158	1	a. ehrenfeucht
159	1	d. haussler
160	1	m. kearns
161	1	l. valiant.
162	1	m. feder
163	1	y. freund
164	1	y. mansour.
165	1	robert e. schapire.
166	1	yoav freund.
167	1	y. freund
168	1	h. s. seung
169	1	e. shamir
170	1	n. tishby.
171	1	yoav freund.
172	1	freund
173	1	haussler
174	1	d.
175	1	y. freund
176	1	m. j. kearns
177	1	d. ron
178	1	r. rubinfeld
179	1	r. e. schapire
180	1	l. sellie.
181	1	yoav freund.
182	1	yoav freund
183	1	h. sebastian seung
184	1	eli shamir
185	1	naftali tishby.
186	1	r. e. schapire.
187	1	freund
188	1	y. & schapire
189	1	r.e.
190	1	freund
191	1	y.
192	1	& schapire
193	1	r. e.
194	1	d. ron.
195	1	freud
196	1	y.
197	1	kearns
198	1	m.
199	1	mansour
200	1	y. ron
201	1	d.
202	1	rubinfeld
203	1	r.
204	1	shapire
205	1	r. e.
206	1	y. freund.
207	1	r. schapire.
208	1	robert e. schapire.
209	1	freund
210	1	schapire
211	1	r.e.
212	1	freund
213	1	y.
214	1	schapire
215	1	r. e.
216	1	freund
217	1	y. & schapire
218	1	r. e.
219	1	freund
220	1	y.
221	1	schapire
222	1	r. e.
223	1	singer
224	1	y.
225	1	& warmuth
226	1	m. k.
227	1	freund
228	1	y.
229	1	seung
230	1	h. s.
231	1	shamir
232	1	e.
233	1	& tishby
234	1	n.
235	1	y. mansour.
236	1	goldman
237	1	s.
238	1	rivest
239	1	r.
240	1	schapire
241	1	r.
242	1	goldman
243	1	s.
244	1	kearns
245	1	m. j.
246	1	schapire
247	1	r.
248	1	sally a. goldman
249	1	michael j. kearns
250	1	robert e. schapire.
251	1	sally a. goldman
252	1	ronald l. rivest
253	1	robert e. schapire.
254	1	goldman
255	1	s. a. & kearns
256	1	m. j.
257	1	s. a. goldman
258	1	r. l. rivest
259	1	r. e. schapire.
260	1	m. j. kearns.
261	1	d. haussler
262	1	m. kearns
263	1	n. littlestone
264	1	m. warmuth.
265	1	d. haussler
266	1	m. kearns
267	1	n. littlestone
268	1	m. k. warmuth.
269	1	haussler
270	1	d.
271	1	kearns
272	1	m. j.
273	1	schapire
274	1	r.
275	1	d. haussler
276	1	r.
277	1	haussler
278	1	d.
279	1	kearns
280	1	schapire
281	1	r.
282	1	d. haussler
283	1	m. kearns
284	1	h. s. seung
285	1	n. tishby.
286	1	d. haussler
287	1	m. kearns
288	1	h.s. seung
289	1	n. tishby.
290	1	r.e. schapire.
291	1	david p. helmbold
292	1	robert e. schapire
293	1	yoram singer
294	1	manfred k. warmuth.
295	1	d. helmbold
296	1	r. e. schapire
297	1	y. singer
298	1	m. k. warmuth.
299	1	helmbold
300	1	d. p.
301	1	schapire
302	1	r. e.
303	1	singer
304	1	y.
305	1	warmuth
306	1	m. k.
307	1	helmbold
308	1	d. p.
309	1	& schapire
310	1	r. e.
311	1	d.p. helmbold
312	1	r.e. schapire
313	1	y. singer
314	1	m.k. warmuth.
315	1	h. kautz
316	1	m. kearns
317	1	b. selman.
318	1	kautz
319	1	h. a.
320	1	kearns
321	1	m. j.
322	1	& selman.
323	1	m. kearns
324	1	m. li
325	1	l. pitt
326	1	l. g. valiant.
327	1	kearns
328	1	m. j.
329	1	li
330	1	m.
331	1	pitt
332	1	l.
333	1	valiant
334	1	l.
335	1	kearns
336	1	li
337	1	m.
338	1	michael kearns.
339	1	l. g. valiant.
340	1	l. pitt.
341	1	michael j. kearns.
342	1	j. e. payne.
343	1	r. schapire.
344	1	kearns
345	1	m.
346	1	kearns
347	1	m. j.
348	1	r. e. schapire
349	1	l. m. sellie.
350	1	m. li.
351	1	m. kearns.
352	1	h. sebastian seung.
353	1	m. kearns
354	1	y.mansour
355	1	d. ron
356	1	r. rubinfeld
357	1	r.e. schapire
358	1	l. sellie.
359	1	u. v. vazirani.
360	1	r.e. schapire.
361	1	l. valiant.
362	1	m. kearns
363	1	r. schapire
364	1	l. sellie.
365	1	kearns
366	1	m.
367	1	li
368	1	m.
369	1	valiant
370	1	l.
371	1	m. kearns
372	1	y. mansour
373	1	d. ron
374	1	r. rubinfeld
375	1	r. schapire
376	1	l. sellie.
377	1	kearns
378	1	m.
379	1	mansour
380	1	y.
381	1	ng
382	1	a.
383	1	ron
384	1	d.
385	1	kearns
386	1	m.
387	1	kearns
388	1	y.
389	1	kearns
390	1	m.
391	1	mansour
392	1	y.
393	1	ng
394	1	a. y.
395	1	& ron
396	1	d.
397	1	m. kearns
398	1	y. mansour
399	1	a. ng,
400	1	kearns
401	1	ron
402	1	d.
403	1	satinder singh.
404	1	m. kearns
405	1	y. mansour
406	1	a. ng.
407	1	d. d. lewis
408	1	r. e. schapire
409	1	j. p. callan
410	1	r. papka.
411	1	littlestone
412	1	n
413	1	schapire
414	1	warmuth
415	1	m.,
416	1	rivest
417	1	r. & schapire
418	1	r.
419	1	r. schapire.
420	1	rivest
421	1	r. l.
422	1	& schapire
423	1	r. e.
424	1	r. rivest,
425	1	r. schapire.
426	1	r. schapire.
427	1	robert e. schapire
428	1	yoav freund
429	1	peter bartlett
430	1	wee sun lee.
431	1	schapire
432	1	r. e.
433	1	r. schapire.
434	1	robert e. schapire.
435	1	robert e. schapire,
436	1	r. e. schapire.
437	1	robert e. schapire.
438	1	r. e. schapire.
439	1	r. e. schapire
440	1	l. m. sellie.
441	1	schapire
442	1	r. e. & warmuth
443	1	m. k.
444	1	schapire
445	1	r.e.
446	1	y. freund,
447	1	l. m. sellie.
448	1	schapire
449	1	r.e.
450	1	schapire r.e.
451	1	freund y.
452	1	bartlett p.
453	1	lee w.s.:
454	1	ron kohavi wolpert
455	1	d. h.
456	1	robert e. schapire.
457	1	schapire
458	1	r. e.
459	1	schapire
460	1	r. & singer
461	1	y.
462	1	yoram singer. boostexter:
463	1	robert e. schapire yoram singer.
464	2	in proc. 36th annual symposium on foundations of computer science,	los alamitos, ca:
465	2	in pre-proceedings of crypto '93,	-
466	2	proceedings of the 26th annual acm symposium on theory of computing,	-
467	2	in proceedings of the twenty-fifth annual acm symposium on the theory of computing,	-
468	2	in advances in neural information processing systems 10,	-
469	2	in proceedings of the 13th international conference on machine learning,	-
470	2	advances in neural information processing systems,	-
471	2	advances in neural information processing systems,	-
472	2	in proceedings colt-88.	-
473	2	information and computation,	-
474	2	in proc. of ieee information theory conference,	-
475	2	-	-
476	2	in proceedings of the third annual workshop on computational learning theory,	-
477	2	in advances in neural informations processing systems 5,	san mateo, ca, 1992.
478	2	in proceedings of the fifth annual workshop on computational learning theory,	-
479	2	in advances in neural information processing systems iv (denver 1992),	-
480	2	proceedings of the 25th annual acm symposium on theory of computing (pp.	san-diego, ca:
481	2	phd thesis,	-
482	2	in advances in neural information processing systems,	cambridge, ma, 1993.
483	2	in proceedings of the second european conference on computational learning theory,	-
484	2	lecture notes in artificial intelligence,	berlin, germany:
485	2	tech. rep.,	murray hill, nj.
486	2	proceedings of the 1995 conference on computational learning theory,	-
487	2	proceedings of the 36 th annual symposium on foundations of computer science.	-
488	2	in proceedings of the 9th annual conference on computational learning theory,	-
489	2	in pro ceedings of the 9th annual conference on computational learning theory,	-
490	2	in proceedings of the 13th international conference on machine learning.	-
491	2	unpublished manuscript,	-
492	2	unpublished manuscript.	-
493	2	journal of computer and system sciences ,55(1),	-
494	2	in proceedings of the twentyninth annual acm symposium on theory of computing.	-
495	2	machine learning,	-
496	2	proceedings of the third european conference on computational learning theory (eurocolt'97), volume 1208 of lecture notes in computer science,	berlin,
497	2	in proceedings of 30th annual symposium on foundation of computer science.	-
498	2	in proceedings of the thirty first annual ieee symposium on foundations of computer science (focs-90),	-
499	2	in proceedings of colt '90,	-
500	2	technical report mit/lcs/tm-413,	-
501	2	proceedings of the fourth annual workshop on computational learning theory (pp.	santa cruz, ca:
502	2	siam journal on computing,	-
503	2	journal of computer and system sciences,	-
504	2	technical report number ucsc-crl-88-06,	-
505	2	information and computation,	-
506	2	in proceedings of the fourth annual conference on computational learning theory (colt-91),	-
507	2	preprint.	-
508	2	-	-
509	2	proceedings of the seventh annual acm conference on computational learning theory,	new york, 1994.
510	2	machine learning,	-
511	2	in proceedings of the eighth annual conference on computational learning theory,	-
512	2	in proceedings of the eighth annual conference on computational learning theory,	-
513	2	in proc. 13th international conference on machine learning,	san francisco,
514	2	-	-
515	2	machine learning,	-
516	2	machine learning,	27:97119,
517	2	in aaai-93,	-
518	2	artificial intelligence,	-
519	2	in proceedings of the nineteenth annual acm symposium on theory of computing,	new york, new york,
520	2	in proceedings of the fourth international conference on machine learning (ml-87),	-
521	2	in proceedings stoc-88.	-
522	2	(unpublished),	-
523	2	in proceedings of the 21 st annual acm symposium on theory of computing,	new york,
524	2	in proceedings of the second annual workshop on computational learning theory,	santa cruz, california,
525	2	phd thesis,	-
526	2	in proceedings of the winter simulation conference,	-
527	2	proceedings of the 31st annual symposium on foundations of computer science (pp.	-
528	2	in proc. of the national conference on artificial intelligence (1992),	-
529	2	in proc. 5th annu. workshop on comput. learning theory,	new york, ny.
530	2	siam j. comput.,	-
531	2	in proc. 25th annu. acm sympos. theory comput.,	new york, ny,
532	2	in proceedings of colt '93,	-
533	2	in the 25th annual acm symposium on theory of computing,	-
534	2	57-62.	-
535	2	journal of computer and system sciences,	-
536	2	journal of the association for computing machinery,	-
537	2	machine learning,	-
538	2	acm 41,	-
539	2	in proc. 26th stoc,	-
540	2	in proceedings colt-95.	-
541	2	advances in neural information processing systems, number 8 in nips.	-
542	2	to appear in proceedings of the 28th acm symposium on the theory of computing.	new york, ny.
543	2	machine learning,	-
544	2	proc. 13th conference on uncertainty in artificial intelligence,	-
545	2	to appear in proceedings of the eleventh annual acm conference on computational learning theory.	-
546	2	in neural information processing systems 12.	-
547	2	unpublished manuscript.	-
548	2	in proc. of the 19th annual international acm-sigir conference on research and development in information retrieval,	-
549	2	in progress.	-
550	2	in proceedings of the fourth international workshop on machine learning,	irvine, ca.
551	2	proceedings of the 28th ieee symposium on foundations of computer science,	-
552	2	in proceedings of the 21th acm symp. on theory of computing,	-
553	2	ietf,	-
554	2	information and computation,	-
555	2	journal of the association for computing machinery,	-
556	2	annals of statistics,	-
557	2	master's thesis,	cambridge, ma.
558	2	proceedings of the 30th i.e.e.e. symposium on the foundations of computer science,	-
559	2	machine learning,	-
560	2	tech. report mit/lcs/tm-431,	-
561	2	technical report mit/lcs/tr-493,	-
562	2	in computation learning theory: proceedings of the fourth annual workshop,	-
563	2	-	cam bridge, ma,
564	2	in proceedings of the sixth annual acm workshop on computational learning theory.	-
565	2	in machine learning: proceedings of the eleventh international conference,	-
566	2	in eurocolt '95,pp.	-
567	2	j. of computer and system sciences,	-
568	2	-	-
569	2	in proceedings of the fourteenth international conference on machine learning,	-
570	2	neural networks 5,	-
571	2	in machine learning: proceedings of the fourteenth international conference,	-
572	2	tech. rep.,	-
573	2	in `proceedings of the eleventh annual conference on computational learning theory'.	-
574	2	unpublished manuscript,	-
575	2	-	-
576	3	ieee computer society press,
577	3	springer,
578	3	acm press.
579	3	morgan kaufmann,
580	3	-
581	3	morgan kaufmann,
582	3	morgan kaufmann,
583	3	morgan kaufmann,
584	3	morgan kaufmann.
585	3	-
586	3	ieee,
587	3	-
588	3	morgan kaufmann.
589	3	morgan kaufmann.
590	3	acm press,
591	3	and r.
592	3	stoc-93.
593	3	-
594	3	mit press.
595	3	springer-verlag,
596	3	springer-verlag.
597	3	-
598	3	-
599	3	-
600	3	acm press,
601	3	-
602	3	morgan kaufmann,
603	3	springer-verlag,
604	3	-
605	3	springer-verlag,
606	3	-
607	3	-
608	3	springer-verlag,
609	3	-
610	3	ieee computer society press.
611	3	morgan kaufmann,
612	3	-
613	3	morgan kaufmann.
614	3	-
615	3	-
616	3	morgan kaufmann publishers,
617	3	morgan kaufmann,
618	3	morgan kaufmann, inc.
619	3	-
620	3	-
621	3	acm.
622	3	-
623	3	acm press.
624	3	-
625	3	morgan kaufmann,
626	3	-
627	3	-
628	3	-
629	3	aaai press.
630	3	-
631	3	acm press.
632	3	morgan kauf-mann.
633	3	acm press,
634	3	-
635	3	stoc-89.
636	3	morgan kaufmann publishers,
637	3	mit press,
638	3	-
639	3	ieee computer society press.
640	3	-
641	3	acm press,
642	3	-
643	3	acm press,
644	3	-
645	3	-
646	3	the mit press,
647	3	-
648	3	-
649	3	-
650	3	-
651	3	acm,
652	3	acm press,
653	3	morgan kaufmann,
654	3	acm press:
655	3	morgan kaufmann.
656	3	morgan kaufmann,
657	3	-
658	3	mit press, (to appear),
659	3	-
660	3	hartung-gorre verlag,
661	3	-
662	3	morgan kaufmann,
663	3	ieee,
664	3	acm,
665	3	-
666	3	springer,
667	3	-
668	3	-
669	3	-
670	3	-
671	3	kluwer academic publishers.
672	3	-
673	3	mit press,
674	3	-
675	3	mit press,
676	3	-
677	3	morgan kaufmann.
678	3	springer verlag,
679	3	-
680	3	-
681	3	morgan kaufmann,
682	3	-
683	3	morgan kaufmann,
684	3	-
685	3	-
686	3	-
687	3	-
